name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Chrome
        run:  npx playwright install chromium

      - name: Generate Prisma Client
        env:
          DATABASE_URL: "postgresql://user:password@localhost:5432/testdb?schema=public"
        run: npx prisma generate

      - name: Run Lint
        run: pnpm run lint

      - name: Run Tests
        env:
          DATABASE_URL: "postgresql://user:password@localhost:5432/testdb?schema=public"
          
        run: pnpm run test